VALID_STOREY_RANGES = [
    "01 TO 03", "04 TO 06", "07 TO 09", "10 TO 12", "13 TO 15",
    "16 TO 18", "19 TO 21", "22 TO 24", "25 TO 27", "28 TO 30",
    "31 TO 33", "34 TO 36", "37 TO 39", "40 TO 42", "43 TO 45",
    "46 TO 48", "49 TO 51",
]

VALID_TOWNS = [
    "ANG MO KIO", "BEDOK", "BISHAN", "BUKIT BATOK", "BUKIT MERAH",
    "BUKIT PANJANG", "BUKIT TIMAH", "CENTRAL AREA", "CHOA CHU KANG",
    "CLEMENTI", "GEYLANG", "HOUGANG", "JURONG EAST", "JURONG WEST",
    "KALLANG/WHAMPOA", "MARINE PARADE", "PASIR RIS", "PUNGGOL",
    "QUEENSTOWN", "SEMBAWANG", "SENGKANG", "SERANGOON", "TAMPINES",
    "TOA PAYOH", "WOODLANDS", "YISHUN",
]

VALID_FLAT_TYPES = [
    "1 ROOM", "2 ROOM", "3 ROOM", "4 ROOM", "5 ROOM",
    "EXECUTIVE", "MULTI-GENERATION",
]

# Used when callers omit flat_type / flat_model (bot collects town + block + storey + area only).
DEFAULT_FLAT_TYPE = "4 ROOM"
DEFAULT_FLAT_MODEL = "MODEL A"

VALID_FLAT_MODELS = [
    "2-ROOM", "3GEN", "ADJOINED FLAT", "APARTMENT", "DBSS",
    "EXECUTIVE MAISONETTE", "IMPROVED", "IMPROVED MAISONETTE",
    "MAISONETTE", "MODEL A", "MODEL A MAISONETTE", "MODEL A2",
    "MODEL B", "MULTI GENERATION", "NEW GENERATION", "PREMIUM APARTMENT",
    "PREMIUM APARTMENT LOFT", "PREMIUM MAISONETTE", "SIMPLIFIED",
    "STANDARD", "TERRACE",
]
