VALID_TOWNS = [
    "ANG MO KIO", "BEDOK", "BISHAN", "BUKIT BATOK", "BUKIT MERAH",
    "BUKIT PANJANG", "BUKIT TIMAH", "CENTRAL AREA", "CHOA CHU KANG",
    "CLEMENTI", "GEYLANG", "HOUGANG", "JURONG EAST", "JURONG WEST",
    "KALLANG/WHAMPOA", "MARINE PARADE", "PASIR RIS", "PUNGGOL",
    "QUEENSTOWN", "SEMBAWANG", "SENGKANG", "SERANGOON", "TAMPINES",
    "TOA PAYOH", "WOODLANDS", "YISHUN",
]

VALID_FLAT_TYPES = [
    "1 ROOM", "2 ROOM", "3 ROOM", "4 ROOM", "5 ROOM",
    "EXECUTIVE", "MULTI-GENERATION",
]

VALID_FLAT_MODELS = [
    "2-ROOM", "3GEN", "ADJOINED FLAT", "APARTMENT", "DBSS",
    "EXECUTIVE MAISONETTE", "IMPROVED", "IMPROVED MAISONETTE",
    "MAISONETTE", "MODEL A", "MODEL A MAISONETTE", "MODEL A2",
    "MODEL B", "MULTI GENERATION", "NEW GENERATION", "PREMIUM APARTMENT",
    "PREMIUM APARTMENT LOFT", "PREMIUM MAISONETTE", "SIMPLIFIED",
    "STANDARD", "TERRACE",
]
